#title: "Columna de Isabel Abedrapo"
#description: "Revisión por pares sin ceguera"

theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
author:
  name: Isabel Abedrapo Rosen
  email: isa.abedrapo@gmail.com

